// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAC0lgsD_K86fhmpwaZWpEoFE6rVjMLafU',
    appId: '1:1082478194715:web:5f910f904c51234ca2c8be',
    messagingSenderId: '1082478194715',
    projectId: 'yno-app-e96f5',
    authDomain: 'yno-app-e96f5.firebaseapp.com',
    storageBucket: 'yno-app-e96f5.firebasestorage.app',
    measurementId: 'G-DCF0FQ30XF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPjUowMJYtDFSlU2NoF1o99Ec-zf0zz_I',
    // org.nellab.yno — re-registered 2026-08-29 (§76). The old
    // com.example.ynoapp app was deleted; its appId ended 7946933b7c0efc91.
    appId: '1:1082478194715:android:887a9e0ca1144002a2c8be',
    messagingSenderId: '1082478194715',
    projectId: 'yno-app-e96f5',
    storageBucket: 'yno-app-e96f5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBD8R6_EfyX9GYX5rbm9dxLk3D_ZJOx8SU',
    appId: '1:1082478194715:ios:30c6901b6354fdfca2c8be',
    messagingSenderId: '1082478194715',
    projectId: 'yno-app-e96f5',
    storageBucket: 'yno-app-e96f5.firebasestorage.app',
    iosBundleId: 'com.example.ynoapp',
  );
}
